### ISSUE TITLE
Permision Denied

### ISSUE THREAD

**Issue by fabestine1** [goclone-dev/goclone#15]
after installing Goclone I tried to copy a website but it's showing the error below. I am using WSL in windows 10. Please is there a way to resolve this or am I doing something wrong?

2021/08/03 10:22:39 mkdir /mnt/c/Windows/system32/tesla.com: permission denied
2021/08/03 10:22:39 mkdir /mnt/c/Windows/system32/tesla.com: permission denied
2021/08/03 10:22:39 mkdir /mnt/c/Windows/system32/tesla.com: permission denied
2021/08/03 10:22:39 mkdir /mnt/c/Windows/system32/tesla.com: permission denied
2021/08/03 10:22:39 open /mnt/c/Windows/system32/tesla.com/index.html: no such file or directory
Extracting -->  https://tesla.com
panic: open /mnt/c/Windows/system32/tesla.com/index.html: no such file or directory

goroutine 18 [running]:
github.com/imthaghost/goclone/crawler.HTMLExtractor(0xc0002a42a0, 0x11, 0xc0000fa180, 0x21)
        /Users/ghost/go/src/github.com/imthaghost/goclone/crawler/html.go:26 +0x2d3
github.com/imthaghost/goclone/crawler.Collector.func4(0xc000198780)
        /Users/ghost/go/src/github.com/imthaghost/goclone/crawler/collector.go:52 +0xc4
github.com/gocolly/colly.(*Collector).handleOnRequest(0xc0000bb860, 0xc000198780)
        /Users/ghost/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:924 +0x66
github.com/gocolly/colly.(*Collector).fetch(0xc0000bb860, 0xc0002a4260, 0x11, 0xa85a26, 0x3, 0x1, 0x0, 0x0, 0xc0001df7f0, 0xc0002b8000, ...)
        /Users/ghost/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:586 +0x176
created by github.com/gocolly/colly.(*Collector).scrape
        /Users/ghost/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:532 +0x3b1

**Comment by fabestine1** [comment]
I also tried adding https: and still the same problem

**Comment by mesaglio** [comment]
Hi!
Test run command in other folder like desktop.
I suspect it is due to a permission problem on system32.

**Comment by mesaglio** [comment]
Closed for inactivity.
