### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by atharva20-coder** [goclone-dev/goclone#16]
As going step by step through installation manual I got stuck over this issue of which I attached screenshot.

 `C:\Users\hp\go/src/github.com/imthaghost/goclone/cmd/goclone`

![Screenshot 2021-08-05 231006](https://user-images.githubusercontent.com/69634375/128396285-83240319-ac9f-48b6-8951-891eb7821431.png)

**Comment by benwaldner** [comment]
I am getting the same error tho. Couldnt find out why. I am also forced to use windows. :/ But on linux one could just cd into the /bin folder and call it through ./goclone site.com. Also it says one linux one should use go install pkt@latest.

**Comment by yezihack** [comment]
> As going step by step through installation manual I got stuck over this issue of which I attached screenshot.
> 
> `C:\Users\hp\go/src/github.com/imthaghost/goclone/cmd/goclone`
> 

Your must set gopath directory, use `go env |findstr "GOPATH"` command. 
cmd -> use command this  `go get -x github.com/imthaghost/goclone`  can be installed, Don't use any other commands.  see below.

![image](https://user-images.githubusercontent.com/11530866/134519644-599649a7-6830-4ef8-8e99-3a2b046a04ea.png)

**Comment by sk0x1234** [comment]
im facing kind of another issue. any helpl?

![image](https://user-images.githubusercontent.com/18193527/140001834-284bb89d-285f-4dab-b84c-04c13091662f.png)

**Comment by mesaglio** [comment]
Sorry for the late reply.
I got the Windows installation working.
We need to update the readme installation documentation.
Try to find the project above the package in your GOPATH.

![image](https://user-images.githubusercontent.com/29051129/162643145-d3eba614-d450-4509-a02d-dd9c8fb8eb32.png)

**Comment by mesaglio** [comment]
@atharva20-coder can you check again with this information?

**Comment by mesaglio** [comment]
I close for inactivity
