### ISSUE TITLE
Why can't I find the SRC directory in my $GOPATH, But I can find goclone in the bin folder

### ISSUE THREAD

**Issue by naohwen** [goclone-dev/goclone#20]
My newly installed go version is go1.16.9

I can only download one web page by using the command. Can't the crawler traverse all the pages of the website

**Comment by imthaghost** [comment]
Hey @naohwen currently the tool only clones the top layer of a site. There is a ticket for doing a given depth of how many pages get clone got a given site as seen [here](https://www.notion.so/0f3cb918168b48ffa5072c6ee39281ee?v=5330c26bd2d747dfac07882347b4a1df&p=6563506f01344680a25c09f9ab92fc22).
