### ISSUE TITLE
Instagram 

### ISSUE THREAD

**Issue by Hugorino11** [goclone-dev/goclone#36]
https://www.instagram.com

**Comment by Hugorino11** [comment]
Usage:
  goclone <https://www.instagram.com/> [flags]

Flags:
  -C, --cookie strings        Pre-set these cookies
  -h, --help                  help for goclone
  -o, --open                  Automatically open project in deafult browser
  -p, --proxy_string string   Proxy connection string. Support http and socks5 https://pkg.go.dev/github.com/gocolly/colly#Collector.SetProxy
  -s, --serve                 Serve the generated files using Echo.
  -u, --user_agent string     Custom User Agent

**Comment by mesaglio** [comment]
I close by duplicate.
