### ISSUE TITLE
Usage: login Instagram 

### ISSUE THREAD

**Issue by Hugorino11** [goclone-dev/goclone#37]
Usage:
  goclone <https://www.instagram.com/> [flags]

Flags:
  -C, --cookie strings        Pre-set these cookies
  -h, --help                  help for goclone
  -o, --open                  Automatically open project in deafult browser
  -p, --proxy_string string   Proxy connection string. Support http and socks5 https://pkg.go.dev/github.com/gocolly/colly#Collector.SetProxy
  -s, --serve                 Serve the generated files using Echo.
  -u, --user_agent string     Custom User Agent

_Originally posted by @Hugorino11 in https://github.com/imthaghost/goclone/issues/36#issuecomment-1100472089_

**Comment by mesaglio** [comment]
Hi there, can you specify the issue?

**Comment by mesaglio** [comment]
I close by duplicate.
