### ISSUE TITLE
how to uninstall?

### ISSUE THREAD

**Issue by NikLEWAN** [goclone-dev/goclone#43]
it does not work, it can clone some websites but not all.

how do i uninstall all the installed packages or where are they downloaded to just in the main folder somewhere?

**Comment by imthaghost** [comment]
[If you installed with Brew](https://osxdaily.com/2018/07/29/uninstall-packages-homebrew-mac/):

`brew uninstall goclone`

If you installed with Go:

`rm -rf $GOPATH/src/github.com/imthaghost/goclone`
