### ISSUE TITLE
goclone doesn't clone a site

### ISSUE THREAD

**Issue by picklit** [goclone-dev/goclone#6]
I was experimenting with your 'goclone' and it seems to only clone the home page, not an entire site. 
 It doesn't seem to even attempt to crawl site links to clone more pages of the site.

**Comment by imthaghost** [comment]
Thanks for experimenting with the tool! I'll add a features section in the README with the completed and incomplete parts of the tool. Currently it only clones the top level of the site, I'm figuring out an efficient way of grabbing all pages with user-specified depth. (how many pages the clone should go). Feel free to also give ideas and also start contributing when I start working on this portion. Thanks again.
